# Generated by Django 5.0.2 on 2024-12-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning', '0003_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='user',
        ),
    ]
