# Generated by Django 5.0.2 on 2024-12-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learning', '0005_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
